const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });
const Package = require('../models/Package');

const MONGODB_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/toursdb';

// Comprehensive India tour packages data
const packagesData = [
  // GOA
  {
    title: 'North Goa Beach Explorer',
    description: 'Experience vibrant beaches, nightlife, and Portuguese heritage of North Goa. Visit famous beaches like Baga, Calangute, and Anjuna. Enjoy water sports, beach parties, authentic Goan cuisine, and explore historic Fort Aguada.',
    destination: 'North Goa',
    state: 'Goa',
    price: 8999,
    duration: { days: 3, nights: 2 },
    category: 'Beach',
    hotel: { name: 'Baga Beach Resort', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC Bus from major cities + local cab' },
    highlights: ['Baga Beach', 'Calangute Beach', 'Anjuna Flea Market', 'Fort Aguada', 'Water Sports', 'Beach Shacks'],
    inclusions: ['AC Transportation', 'Hotel Stay', 'Breakfast & Dinner', 'Local Sightseeing', 'Professional Guide', 'Water Sports Activities', 'Entry Tickets'],
    exclusions: ['Lunch', 'Personal Expenses', 'Travel Insurance'],
    rating: 4.5,
    reviewCount: 245,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Popular%20Goa%20beaches%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Arrival & Beach Exploration', description: 'Arrive in Goa, hotel check-in, visit Calangute and Baga beaches', activities: ['Hotel Check-in', 'Calangute Beach', 'Baga Beach', 'Beach Shacks Dinner'] },
      { day: 2, title: 'Water Sports & Fort', description: 'Morning water sports at Baga, afternoon Fort Aguada and Anjuna Beach visit', activities: ['Parasailing', 'Jet Ski', 'Banana Boat', 'Fort Aguada', 'Anjuna Beach'] },
      { day: 3, title: 'Flea Market & Departure', description: 'Visit Anjuna Flea Market for shopping, checkout', activities: ['Anjuna Flea Market', 'Shopping', 'Hotel Checkout', 'Departure'] }
    ]
  },
  {
    title: 'South Goa Luxury Escape',
    description: 'Discover the serene and pristine beaches of South Goa. Enjoy luxury resorts, tranquil beaches like Palolem and Colva, visit ancient churches, spice plantations, and indulge in Goan seafood delicacies with candlelight dinners.',
    destination: 'South Goa',
    state: 'Goa',
    price: 18999,
    duration: { days: 4, nights: 3 },
    category: 'Honeymoon',
    hotel: { name: 'Luxury Beach Resort Palolem', rating: 5, type: 'Luxury' },
    transport: { type: 'Mixed', details: 'Private cab transfers throughout' },
    highlights: ['Palolem Beach', 'Colva Beach', 'Dudhsagar Falls', 'Spice Plantation', 'Old Goa Churches', 'Spa Session'],
    inclusions: ['AC Transportation', 'Luxury Hotel Stay', 'All Meals', 'Private Cab', 'Professional Guide', 'Candlelight Dinner', 'Spa Session', 'Entry Tickets'],
    exclusions: ['Airfare', 'Personal Expenses', 'Travel Insurance'],
    rating: 4.8,
    reviewCount: 189,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Luxury%20beach%20resorts%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Arrival & Relaxation', description: 'Private transfer to luxury resort, evening beach walk at Palolem', activities: ['Airport Pickup', 'Resort Check-in', 'Welcome Drink', 'Palolem Beach Walk', 'Candlelight Dinner'] },
      { day: 2, title: 'Beach & Plantation', description: 'Morning at Colva Beach, afternoon spice plantation tour', activities: ['Colva Beach', 'Spice Plantation Tour', 'Traditional Goan Lunch', 'Spa Session'] },
      { day: 3, title: 'Dudhsagar Falls', description: 'Full day trip to Dudhsagar Falls, jeep safari through forests', activities: ['Dudhsagar Falls', 'Jeep Safari', 'Waterfall Trek', 'Swimming', 'Evening Relaxation'] },
      { day: 4, title: 'Old Goa & Departure', description: 'Visit Old Goa churches, shopping, departure', activities: ['Basilica of Bom Jesus', 'Se Cathedral', 'Shopping', 'Departure'] }
    ]
  },
  {
    title: 'Goa Water Sports Package',
    description: 'An adrenaline-packed adventure package featuring all popular water sports in Goa. Perfect for adventure enthusiasts looking for parasailing, scuba diving, jet skiing, banana boat rides, and speed boating.',
    destination: 'Goa',
    state: 'Goa',
    price: 6999,
    duration: { days: 2, nights: 1 },
    category: 'Adventure',
    hotel: { name: 'Beach Side Inn', rating: 3, type: 'Budget' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Parasailing', 'Scuba Diving', 'Jet Ski', 'Banana Boat', 'Speed Boat', 'Snorkeling'],
    inclusions: ['AC Transportation', 'Hotel Stay', 'Breakfast', 'All Water Sports', 'Professional Instructors', 'Safety Equipment', 'Photography'],
    exclusions: ['Lunch & Dinner', 'Personal Expenses', 'Insurance'],
    rating: 4.6,
    reviewCount: 312,
    images: ['https://image.pollinations.ai/prompt/Parasailing%20and%20water%20sports%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Water Sports Day', description: 'Morning check-in, full day water sports at Baga Beach', activities: ['Hotel Check-in', 'Parasailing', 'Jet Ski', 'Banana Boat Ride', 'Speed Boat'] },
      { day: 2, title: 'Scuba & Departure', description: 'Morning scuba diving session, checkout', activities: ['Scuba Diving', 'Snorkeling', 'Beach Time', 'Checkout', 'Departure'] }
    ]
  },

  // KERALA
  {
    title: 'Munnar Tea Garden Tour',
    description: 'Explore the lush green tea plantations of Munnar, visit tea museums, enjoy scenic viewpoints, spot wildlife at Eravikulam National Park, and experience the cool mountain climate of God\'s Own Country.',
    destination: 'Munnar',
    state: 'Kerala',
    price: 11999,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Munnar Tea County', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus from Cochin + local cab' },
    highlights: ['Tea Plantations', 'Mattupetty Dam', 'Echo Point', 'Eravikulam National Park', 'Tea Museum', 'Top Station'],
    inclusions: ['AC Transportation', 'Hotel Stay', 'All Meals', 'Local Sightseeing', 'Professional Guide', 'Entry Tickets', 'Tea Factory Visit'],
    exclusions: ['Personal Expenses', 'Travel Insurance', 'Tips'],
    rating: 4.7,
    reviewCount: 456,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Tea%20plantations%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Arrival & Tea Gardens', description: 'Arrive in Munnar, check-in, visit tea gardens and tea museum', activities: ['Hotel Check-in', 'Tea Plantation Visit', 'Tea Museum', 'Tea Factory Tour', 'Tea Tasting'] },
      { day: 2, title: 'Sightseeing', description: 'Full day Munnar sightseeing - Mattupetty, Echo Point, Top Station', activities: ['Mattupetty Dam', 'Echo Point', 'Kundala Lake', 'Top Station', 'Photo Point'] },
      { day: 3, title: 'Eravikulam & Departure', description: 'Morning visit to Eravikulam National Park, checkout', activities: ['Eravikulam National Park', 'Nilgiri Tahr Spotting', 'Shopping', 'Departure'] }
    ]
  },
  {
    title: 'Alleppey Houseboat Experience',
    description: 'Cruise through the enchanting backwaters of Alleppey in a traditional Kerala houseboat. Enjoy fresh seafood, witness village life, paddy fields, and experience the tranquil beauty of Kerala\'s backwaters.',
    destination: 'Alleppey',
    state: 'Kerala',
    price: 13999,
    duration: { days: 2, nights: 1 },
    category: 'Honeymoon',
    hotel: { name: 'Premium Houseboat', rating: 4, type: 'Premium' },
    transport: { type: 'Mixed', details: 'Houseboat cruise included' },
    highlights: ['Backwater Cruise', 'Traditional Houseboat', 'Kerala Cuisine', 'Village Life', 'Sunset Views', 'Paddy Fields'],
    inclusions: ['AC Houseboat Stay', 'All Meals (Traditional Kerala Food)', 'Houseboat Cruise', 'Welcome Drink', 'Entertainment', 'Photography'],
    exclusions: ['Travel to Alleppey', 'Personal Expenses', 'Tips'],
    rating: 4.9,
    reviewCount: 523,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Houseboats%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Houseboat Check-in & Cruise', description: 'Board houseboat at noon, cruise through backwaters', activities: ['Houseboat Boarding', 'Welcome Drink', 'Backwater Cruise', 'Village Visit', 'Sunset Viewing', 'Traditional Dinner'] },
      { day: 2, title: 'Morning Cruise & Departure', description: 'Early morning cruise, breakfast, check-out', activities: ['Sunrise Viewing', 'Breakfast on Boat', 'Final Cruise', 'Check-out', 'Departure'] }
    ]
  },
  {
    title: 'Wayanad Nature Escape',
    description: 'Discover the pristine beauty of Wayanad with its waterfalls, wildlife sanctuaries, ancient caves, and spice plantations. Perfect for nature lovers and adventure seekers exploring the Western Ghats.',
    destination: 'Wayanad',
    state: 'Kerala',
    price: 10499,
    duration: { days: 3, nights: 2 },
    category: 'Adventure',
    hotel: { name: 'Wayanad Woods', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local jeep' },
    highlights: ['Soochipara Falls', 'Edakkal Caves', 'Banasura Dam', 'Wildlife Sanctuary', 'Trekking', 'Spice Plantation'],
    inclusions: ['AC Transportation', 'Hotel Stay', 'All Meals', 'Sightseeing', 'Trekking Guide', 'Entry Tickets', 'Jeep Safari'],
    exclusions: ['Personal Expenses', 'Insurance', 'Tips'],
    rating: 4.5,
    reviewCount: 287,
    images: ['https://image.pollinations.ai/prompt/Forests%20and%20waterfalls%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Arrival & Waterfalls', description: 'Arrive in Wayanad, check-in, visit Soochipara and Meenmutty waterfalls', activities: ['Hotel Check-in', 'Soochipara Falls Trek', 'Meenmutty Falls', 'Photography', 'Nature Walk'] },
      { day: 2, title: 'Caves & Dam', description: 'Visit Edakkal Caves and Banasura Sagar Dam', activities: ['Edakkal Caves', 'Ancient Rock Carvings', 'Banasura Dam', 'Boating', 'Sunset Point'] },
      { day: 3, title: 'Wildlife & Departure', description: 'Morning wildlife safari, departure', activities: ['Muthanga Wildlife Sanctuary', 'Safari', 'Spice Plantation', 'Shopping', 'Departure'] }
    ]
  },
  {
    title: 'Kerala Backwater Luxury Tour',
    description: 'A premium 6-day Kerala tour covering Cochin, Munnar, Thekkady, Alleppey backwaters, and Kovalam beaches. Experience the complete essence of God\'s Own Country in luxury with ayurvedic treatments.',
    destination: 'Multi-City Kerala',
    state: 'Kerala',
    price: 35999,
    duration: { days: 6, nights: 5 },
    category: 'Honeymoon',
    hotel: { name: 'Luxury Resorts & Houseboats', rating: 5, type: 'Luxury' },
    transport: { type: 'Mixed', details: 'Private AC cab throughout' },
    highlights: ['Munnar Hill Station', 'Thekkady Wildlife', 'Alleppey Houseboat', 'Kovalam Beach', 'Fort Kochi', 'Ayurvedic Spa'],
    inclusions: ['Luxury Hotel Stay', 'Private AC Cab', 'All Meals', 'Houseboat Cruise', 'Ayurvedic Massage', 'All Sightseeing', 'Professional Guide', 'Airport Transfers'],
    exclusions: ['Airfare', 'Personal Expenses', 'Insurance', 'Tips'],
    rating: 4.9,
    reviewCount: 412,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Kerala%20backwaters%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true'],
    itinerary: [
      { day: 1, title: 'Cochin Arrival', description: 'Arrive Cochin, Fort Kochi sightseeing', activities: ['Airport Pickup', 'Chinese Fishing Nets', 'St. Francis Church', 'Jewish Synagogue', 'Dutch Palace'] },
      { day: 2, title: 'Munnar', description: 'Drive to Munnar, tea plantations visit', activities: ['Scenic Drive', 'Tea Plantations', 'Mattupetty Dam', 'Check-in Luxury Resort'] },
      { day: 3, title: 'Munnar Sightseeing', description: 'Full day Munnar exploration', activities: ['Eravikulam Park', 'Echo Point', 'Top Station', 'Tea Museum'] },
      { day: 4, title: 'Thekkady', description: 'Drive to Thekkady, spice plantation and boat ride', activities: ['Periyar Lake Boat Ride', 'Spice Plantation', 'Elephant Ride', 'Martial Arts Show'] },
      { day: 5, title: 'Alleppey Houseboat', description: 'Houseboat experience in backwaters', activities: ['Houseboat Check-in', 'Backwater Cruise', 'Village Visit', 'Sunset Views'] },
      { day: 6, title: 'Departure', description: 'Checkout and departure to Cochin airport', activities: ['Ayurvedic Massage', 'Shopping', 'Airport Drop', 'Departure'] }
    ]
  },

  // TAMIL NADU
  {
    title: 'Ooty Hill Station Tour',
    description: 'Queen of Hills - Experience the Nilgiri Mountain Railway, botanical gardens, Ooty Lake boating, tea estates, Doddabetta Peak scenic viewpoints. Perfect family vacation in pleasant weather.',
    destination: 'Ooty',
    state: 'Tamil Nadu',
    price: 9999,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Sterling Ooty', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local cab' },
    highlights: ['Nilgiri Railway', 'Botanical Garden', 'Ooty Lake', 'Doddabetta Peak', 'Tea Estates', 'Rose Garden'],
    inclusions: ['Transportation', 'Hotel', 'Meals', 'Sightseeing', 'Guide', 'Entry Tickets', 'Toy Train Ride'],
    exclusions: ['Personal Expenses', 'Insurance'],
    rating: 4.6,
    reviewCount: 378,
    images: ['https://image.pollinations.ai/prompt/Tea%20gardens%20and%20hills%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Kodaikanal Family Package',
    description: 'Princess of Hill Stations. Kodaikanal Lake boating, Bryant Park, Coakers Walk, Silver Cascade Falls, Pillar Rocks. Perfect family vacation with pleasant weather and scenic beauty.',
    destination: 'Kodaikanal',
    state: 'Tamil Nadu',
    price: 12499,
    duration: { days: 4, nights: 3 },
    category: 'Family',
    hotel: { name: 'Sterling Kodai Lake', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Kodai Lake', 'Bryant Park', 'Coakers Walk', 'Silver Cascade', 'Pillar Rocks', 'Bear Shola Falls'],
    inclusions: ['AC Transportation', 'Hotel Stay', 'All Meals', 'Sightseeing', 'Boating', 'Guide', 'Tickets'],
    exclusions: ['Personal Expenses', 'Insurance'],
    rating: 4.7,
    reviewCount: 298,
    images: ['https://image.pollinations.ai/prompt/Kodaikanal%20lake%20and%20hills%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Rameshwaram Pilgrimage Tour',
    description: 'Sacred pilgrimage to Ramanathaswamy Temple, Dhanushkodi ghost town, Pamban Bridge. Spiritual journey with temple rituals, holy bath, and religious significance.',
    destination: 'Rameshwaram',
    state: 'Tamil Nadu',
    price: 7999,
    duration: { days: 2, nights: 1 },
    category: 'Pilgrimage',
    hotel: { name: 'Daiwik Hotels', rating: 3, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + local transport' },
    highlights: ['Ramanathaswamy Temple', 'Dhanushkodi', 'Pamban Bridge', 'Ram Setu', 'Temple Rituals', 'Holy Bath'],
    inclusions: ['Transportation', 'Hotel', 'Meals', 'Temple Guide', 'Darshan', 'Pooja Materials'],
    exclusions: ['Train Fare', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 621,
    images: ['https://image.pollinations.ai/prompt/Ramanathaswamy%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Madurai Temple Heritage Tour',
    description: 'Ancient Meenakshi Temple with stunning Dravidian architecture, Thirumalai Nayak Palace, Gandhi Museum, vibrant markets. Rich cultural heritage and temple ceremonies.',
    destination: 'Madurai',
    state: 'Tamil Nadu',
    price: 6499,
    duration: { days: 2, nights: 1 },
    category: 'Cultural',
    hotel: { name: 'Heritage Madurai', rating: 3, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + local transport' },
    highlights: ['Meenakshi Temple', 'Thirumalai Palace', 'Gandhi Museum', 'Local Markets', 'Temple Ceremony', 'Street Food'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast', 'Sightseeing', 'Guide', 'Entry Tickets'],
    exclusions: ['Train Fare', 'Lunch & Dinner', 'Personal Expenses'],
    rating: 4.6,
    reviewCount: 445,
    images: ['https://image.pollinations.ai/prompt/Meenakshi%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // ANDHRA PRADESH & TELANGANA
  {
    title: 'Araku Valley Tour',
    description: 'Scenic hill station with coffee plantations, Borra Caves limestone formations, tribal museums, Katiki Waterfalls. Beautiful Eastern Ghats experience with toy train journey.',
    destination: 'Araku Valley',
    state: 'Andhra Pradesh',
    price: 8999,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Haritha Valley Resort', rating: 3, type: 'Standard' },
    transport: { type: 'Train', details: 'Toy train + bus' },
    highlights: ['Borra Caves', 'Coffee Plantations', 'Tribal Museum', 'Katiki Waterfalls', 'Train Journey', 'Valley Views'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Train Tickets', 'Guide'],
    exclusions: ['Personal Expenses', 'Insurance'],
    rating: 4.5,
    reviewCount: 234,
    images: ['https://image.pollinations.ai/prompt/Araku%20landscapes%20and%20coffee%20plantations%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Tirupati Spiritual Package',
    description: 'Darshan at Tirumala Venkateswara Temple, Sri Padmavathi Temple. VIP darshan arrangement, accommodation, divine spiritual experience at world\'s richest temple.',
    destination: 'Tirupati',
    state: 'Andhra Pradesh',
    price: 9999,
    duration: { days: 2, nights: 1 },
    category: 'Pilgrimage',
    hotel: { name: 'Marasa Sarovar Premiere', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Venkateswara Temple', 'VIP Darshan', 'Padmavathi Temple', 'Akasa Ganga', 'Temple Town', 'Laddu Prasadam'],
    inclusions: ['Transportation', 'Hotel', 'Meals', 'VIP Darshan Tickets', 'Guide', 'Temple Services'],
    exclusions: ['Personal Expenses', 'Donations'],
    rating: 4.8,
    reviewCount: 782,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Tirumala%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Hyderabad Heritage Tour',
    description: 'City of Pearls - Charminar, Golconda Fort, Hussain Sagar Lake, Birla Mandir. Authentic biryani trail, pearl shopping, Qutb Shahi tombs. Rich Nizami heritage.',
    destination: 'Hyderabad',
    state: 'Telangana',
    price: 10999,
    duration: { days: 3, nights: 2 },
    category: 'Cultural',
    hotel: { name: 'Taj Krishna', rating: 4, type: 'Standard' },
    transport: { type: 'Mixed', details: 'Airport pickup + local cab' },
    highlights: ['Charminar', 'Golconda Fort', 'Hussain Sagar', 'Birla Mandir', 'Biryani Trail', 'Pearl Shopping'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast', 'Sightseeing', 'Guide', 'Biryani Lunch', 'Entry Tickets'],
    exclusions: ['Airfare', 'Dinner', 'Personal Expenses'],
    rating: 4.6,
    reviewCount: 412,
    images: ['https://image.pollinations.ai/prompt/Charminar%20and%20heritage%20sites%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Ramoji Film City Package',
    description: 'World\'s largest film city. Studio tours, live shows, adventure rides, vintage cars, gardens, movie sets. Fun-filled family entertainment and Bollywood experience.',
    destination: 'Hyderabad',
    state: 'Telangana',
    price: 5999,
    duration: { days: 2, nights: 1 },
    category: 'Family',
    hotel: { name: 'Hotel Tara', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + film city transport' },
    highlights: ['Film City Tour', 'Live Shows', 'Adventure Rides', 'Vintage Cars', 'Movie Sets', 'Gardens'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast', 'Film City Tickets', 'Tour Guide', 'Lunch'],
    exclusions: ['Personal Expenses', 'Additional Rides'],
    rating: 4.7,
    reviewCount: 567,
    images: ['https://image.pollinations.ai/prompt/Ramoji%20Film%20City%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // MAHARASHTRA
  {
    title: 'Mahabaleshwar Retreat',
    description: 'Strawberry capital with scenic viewpoints Arthur\'s Seat, Venna Lake boating, waterfalls, Pratapgarh Fort. Fresh strawberries and pleasant weather year-round. Perfect weekend retreat.',
    destination: 'Mahabaleshwar',
    state: 'Maharashtra',
    price: 9499,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Brightland Resort', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Arthur\'s Seat', 'Venna Lake', 'Pratapgarh Fort', 'Mapro Garden', 'Strawberry Farms', 'Viewpoints'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Boating', 'Entry Tickets'],
    exclusions: ['Personal Expenses', 'Insurance'],
    rating: 4.5,
    reviewCount: 342,
    images: ['https://image.pollinations.ai/prompt/Hills%20and%20strawberry%20farms%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Lonavala Weekend Tour',
    description: 'Perfect weekend getaway near Mumbai-Pune. Karla caves ancient Buddhist site, Bhushi Dam, Tiger\'s Leap viewpoint, lush greenery during monsoons. Famous chikki shopping.',
    destination: 'Lonavala',
    state: 'Maharashtra',
    price: 6999,
    duration: { days: 2, nights: 1 },
    category: 'Hill Station',
    hotel: { name: 'Fariyas Resort', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus' },
    highlights: ['Tiger\'s Leap', 'Bhushi Dam', 'Karla Caves', 'Lonavala Lake', 'Chikki Shopping', 'Viewpoints'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast & Dinner', 'Sightseeing', 'Guide'],
    exclusions: ['Lunch', 'Personal Expenses'],
    rating: 4.4,
    reviewCount: 498,
    images: ['https://image.pollinations.ai/prompt/Green%20valleys%20and%20waterfalls%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Mumbai City Explorer',
    description: 'Maximum City - Gateway of India, Marine Drive sunset, Elephanta Caves, Bollywood studio tours, street food walks. Colonial architecture and vibrant city life.',
    destination: 'Mumbai',
    state: 'Maharashtra',
    price: 11999,
    duration: { days: 3, nights: 2 },
    category: 'Cultural',
    hotel: { name: 'The Leela Mumbai', rating: 5, type: 'Standard' },
    transport: { type: 'Mixed', details: 'Local trains + cabs' },
    highlights: ['Gateway of India', 'Marine Drive', 'Elephanta Caves', 'Bollywood Tour', 'Street Food Walk', 'Colaba'],
    inclusions: ['Hotel', 'Breakfast', 'Sightseeing', 'Ferry Tickets', 'Bollywood Tour', 'Food Walk'],
    exclusions: ['Airfare', 'Lunch & Dinner', 'Personal Expenses'],
    rating: 4.6,
    reviewCount: 623,
    images: ['/assets/goa_hero_banner_1780120545332.png']
  },
  {
    title: 'Ajanta Ellora Heritage Tour',
    description: 'UNESCO World Heritage caves with ancient rock-cut temples Buddhist and Hindu, intricate paintings, sculptures. Incredible architectural marvels spanning centuries. Bibi Ka Maqbara mini Taj Mahal.',
    destination: 'Aurangabad',
    state: 'Maharashtra',
    price: 13999,
    duration: { days: 4, nights: 3 },
    category: 'Cultural',
    hotel: { name: 'Vivanta Aurangabad', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Flight + cab' },
    highlights: ['Ajanta Caves', 'Ellora Caves', 'Bibi Ka Maqbara', 'Daulatabad Fort', 'Cave Paintings', 'Sculptures'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Guide', 'Entry Tickets', 'Photography'],
    exclusions: ['Airfare', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 456,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Ajanta%20and%20Ellora%20caves%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // RAJASTHAN
  {
    title: 'Jaipur Royal Heritage Tour',
    description: 'Pink City - Amber Fort with elephant ride, City Palace royal residence, Hawa Mahal palace of winds, Jantar Mantar observatory. Royal Rajasthan experience with traditional cuisine and cultural shows.',
    destination: 'Jaipur',
    state: 'Rajasthan',
    price: 12999,
    duration: { days: 4, nights: 3 },
    category: 'Cultural',
    hotel: { name: 'Jai Mahal Palace', rating: 5, type: 'Standard' },
    transport: { type: 'Mixed', details: 'Flight + private cab' },
    highlights: ['Amber Fort', 'City Palace', 'Hawa Mahal', 'Jantar Mantar', 'Jal Mahal', 'Elephant Ride'],
    inclusions: ['Transportation', 'Heritage Hotel', 'All Meals', 'Sightseeing', 'Guide', 'Cultural Show', 'Tickets'],
    exclusions: ['Airfare', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 789,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Palaces%20and%20forts%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Udaipur Lake City Package',
    description: 'City of Lakes - Lake Pichola boat ride, City Palace museum, Jag Mandir island palace, Saheliyon Ki Bari garden. Romantic boat rides, heritage hotels, sunset views. Venice of East.',
    destination: 'Udaipur',
    state: 'Rajasthan',
    price: 15999,
    duration: { days: 4, nights: 3 },
    category: 'Honeymoon',
    hotel: { name: 'Lake Palace Heritage', rating: 5, type: 'Premium' },
    transport: { type: 'Mixed', details: 'Flight + private cab' },
    highlights: ['Lake Pichola', 'City Palace', 'Jag Mandir', 'Saheliyon Ki Bari', 'Boat Ride', 'Sunset Point'],
    inclusions: ['Transportation', 'Luxury Hotel', 'All Meals', 'Private Cab', 'Boat Ride', 'Guide', 'Tickets'],
    exclusions: ['Airfare', 'Personal Expenses'],
    rating: 4.9,
    reviewCount: 612,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Lakes%20and%20palaces%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Jaisalmer Desert Safari',
    description: 'Golden City - Sam Sand Dunes camel safari, desert camping under stars, Jaisalmer Fort living fort, Patwon Ki Haveli. Authentic Rajasthani cultural evening with folk dances.',
    destination: 'Jaisalmer',
    state: 'Rajasthan',
    price: 14999,
    duration: { days: 4, nights: 3 },
    category: 'Adventure',
    hotel: { name: 'Desert Camp + Hotel', rating: 3, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + jeep safari' },
    highlights: ['Sam Sand Dunes', 'Camel Safari', 'Jaisalmer Fort', 'Desert Camp', 'Cultural Evening', 'Haveli Tour'],
    inclusions: ['Transportation', 'Hotel + Camp', 'All Meals', 'Camel Safari', 'Cultural Show', 'Guide', 'Bonfire'],
    exclusions: ['Train Fare', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 534,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Camel%20safari%20and%20desert%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Rajasthan Luxury Tour',
    description: 'Complete Rajasthan - Jaipur Pink City, Jodhpur Blue City, Udaipur Lake City, Jaisalmer Golden City. Royal palaces, desert safaris, luxury heritage stays, complete cultural experiences.',
    destination: 'Multi-City Rajasthan',
    state: 'Rajasthan',
    price: 45999,
    duration: { days: 7, nights: 6 },
    category: 'Honeymoon',
    hotel: { name: 'Heritage Palaces', rating: 5, type: 'Luxury' },
    transport: { type: 'Mixed', details: 'Private cab throughout' },
    highlights: ['Jaipur Palaces', 'Jodhpur Fort', 'Udaipur Lakes', 'Jaisalmer Desert', 'Heritage Hotels', 'Cultural Shows'],
    inclusions: ['Luxury Transportation', 'Heritage Hotels', 'All Meals', 'Sightseeing', 'Private Guide', 'Cultural Shows', 'Tickets'],
    exclusions: ['Airfare', 'Personal Expenses', 'Insurance'],
    rating: 4.9,
    reviewCount: 423,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Luxury%20palaces%20and%20forts%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // HIMACHAL PRADESH
  {
    title: 'Manali Adventure Tour',
    description: 'Himalayan paradise - Solang Valley adventure activities, Rohtang Pass snow point, Beas river rafting, paragliding. Old Manali cafes, Hidimba Temple. Perfect for thrill-seekers and nature lovers.',
    destination: 'Manali',
    state: 'Himachal Pradesh',
    price: 12999,
    duration: { days: 5, nights: 4 },
    category: 'Adventure',
    hotel: { name: 'Snow Valley Resorts', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC Volvo from Delhi' },
    highlights: ['Solang Valley', 'Rohtang Pass', 'River Rafting', 'Paragliding', 'Old Manali', 'Hidimba Temple'],
    inclusions: ['AC Volvo Bus', 'Hotel', 'Breakfast & Dinner', 'Sightseeing', 'Adventure Activities', 'Guide'],
    exclusions: ['Rohtang Pass Permit', 'Lunch', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 678,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Mountains%20and%20adventure%20sports%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Shimla Family Vacation',
    description: 'Queen of Hills - Mall Road shopping, Ridge views, Jakhu Temple Hanuman statue, toy train ride to Kalka. Christ Church, Kufri adventure activities. Classic family hill station vacation.',
    destination: 'Shimla',
    state: 'Himachal Pradesh',
    price: 10999,
    duration: { days: 4, nights: 3 },
    category: 'Family',
    hotel: { name: 'Clarkes Hotel', rating: 4, type: 'Standard' },
    transport: { type: 'Train', details: 'Toy train + bus' },
    highlights: ['Mall Road', 'Ridge', 'Jakhu Temple', 'Toy Train', 'Kufri', 'Christ Church'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Toy Train Tickets', 'Kufri Activities'],
    exclusions: ['Train Fare to Kalka', 'Personal Expenses'],
    rating: 4.6,
    reviewCount: 523,
    images: ['https://image.pollinations.ai/prompt/Shimla%20hills%20and%20town%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Spiti Valley Expedition',
    description: 'High altitude cold desert - Ancient monasteries Key Monastery, Chandratal Lake crescent lake, Kaza town, challenging terrain high passes. Ultimate adventure for experienced travelers seeking offbeat destinations.',
    destination: 'Spiti Valley',
    state: 'Himachal Pradesh',
    price: 24999,
    duration: { days: 8, nights: 7 },
    category: 'Adventure',
    hotel: { name: 'Guesthouses & Camps', rating: 2, type: 'Budget' },
    transport: { type: 'Bus', details: 'SUV + local transport' },
    highlights: ['Key Monastery', 'Chandratal Lake', 'Kaza', 'High Passes', 'Monasteries', 'Pin Valley'],
    inclusions: ['SUV Transportation', 'Accommodation', 'All Meals', 'Permits', 'Local Guide', 'Camping Equipment'],
    exclusions: ['Personal Expenses', 'Insurance', 'Medical Kit'],
    rating: 4.9,
    reviewCount: 287,
    images: ['https://image.pollinations.ai/prompt/Spiti%20Valley%20landscapes%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // UTTARAKHAND
  {
    title: 'Nainital Lake Tour',
    description: 'Lake district - Naini Lake boating central attraction, Mall Road shopping, Naina Peak trekking, Snow View point, Naina Devi Temple. Peaceful Himalayan retreat with pleasant weather.',
    destination: 'Nainital',
    state: 'Uttarakhand',
    price: 9499,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Manu Maharani', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Naini Lake', 'Mall Road', 'Naina Peak', 'Snow View', 'Boating', 'Cable Car'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast & Dinner', 'Sightseeing', 'Boating', 'Cable Car'],
    exclusions: ['Lunch', 'Personal Expenses'],
    rating: 4.5,
    reviewCount: 445,
    images: ['https://image.pollinations.ai/prompt/Nainital%20Lake%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Mussoorie Hills Package',
    description: 'Queen of Hills - Kempty Falls waterfall swimming, Gun Hill cable car ride, Mall Road shopping, Lal Tibba highest point. Scenic views of Doon Valley and snow-capped Himalayan ranges.',
    destination: 'Mussoorie',
    state: 'Uttarakhand',
    price: 8999,
    duration: { days: 3, nights: 2 },
    category: 'Hill Station',
    hotel: { name: 'Jaypee Residency', rating: 4, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local cab' },
    highlights: ['Kempty Falls', 'Gun Hill', 'Mall Road', 'Lal Tibba', 'Cable Car', 'Company Garden'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast & Dinner', 'Sightseeing', 'Cable Car', 'Guide'],
    exclusions: ['Lunch', 'Personal Expenses'],
    rating: 4.4,
    reviewCount: 389,
    images: ['https://image.pollinations.ai/prompt/Mussoorie%20hill%20views%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Char Dham Yatra',
    description: 'Sacred pilgrimage to four holy Hindu temples - Yamunotri source of Yamuna, Gangotri source of Ganga, Kedarnath Shiva temple, Badrinath Vishnu temple. Complete spiritual journey in Himalayas with Rishikesh.',
    destination: 'Uttarakhand',
    state: 'Uttarakhand',
    price: 29999,
    duration: { days: 10, nights: 9 },
    category: 'Pilgrimage',
    hotel: { name: 'Dharamshalas & Hotels', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC coach + helicopter option' },
    highlights: ['Yamunotri', 'Gangotri', 'Kedarnath', 'Badrinath', 'Rishikesh', 'Haridwar'],
    inclusions: ['AC Transportation', 'Accommodation', 'All Meals', 'Temple Guide', 'Puja Materials', 'Permits'],
    exclusions: ['Helicopter Charges', 'Personal Expenses', 'Donations'],
    rating: 4.8,
    reviewCount: 812,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Himalayan%20pilgrimage%20sites%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // JAMMU & KASHMIR
  {
    title: 'Srinagar Paradise Tour',
    description: 'Heaven on Earth - Dal Lake shikara ride, Mughal Gardens Shalimar Bagh Nishat Bagh, houseboat stay floating palace. Paradise for honeymooners with snow-capped Himalayan views. Gulmarg day trip option.',
    destination: 'Srinagar',
    state: 'Jammu & Kashmir',
    price: 16999,
    duration: { days: 5, nights: 4 },
    category: 'Honeymoon',
    hotel: { name: 'Houseboat + Hotel', rating: 4, type: 'Premium' },
    transport: { type: 'Flight', details: 'Airport pickup + private cab' },
    highlights: ['Dal Lake', 'Mughal Gardens', 'Shikara Ride', 'Houseboat Stay', 'Gulmarg Day Trip', 'Saffron Fields'],
    inclusions: ['Transportation', 'Houseboat + Hotel', 'All Meals', 'Shikara Ride', 'Sightseeing', 'Guide'],
    exclusions: ['Airfare', 'Gulmarg Gondola', 'Personal Expenses'],
    rating: 4.9,
    reviewCount: 567,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Dal%20Lake%20and%20houseboats%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Gulmarg Snow Adventure',
    description: 'Skiing paradise - Gondola ride highest cable car, snow sports skiing snowboarding, Apharwat Peak summit. World-class skiing destination with stunning valley views. Asia\'s best ski resort.',
    destination: 'Gulmarg',
    state: 'Jammu & Kashmir',
    price: 18999,
    duration: { days: 4, nights: 3 },
    category: 'Adventure',
    hotel: { name: 'Khyber Himalayan Resort', rating: 5, type: 'Standard' },
    transport: { type: 'Flight', details: 'Srinagar airport + cab' },
    highlights: ['Gondola Ride', 'Skiing', 'Snowboarding', 'Apharwat Peak', 'Snow Activities', 'Golf Course'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Gondola Tickets', 'Skiing Equipment', 'Instructor'],
    exclusions: ['Airfare', 'Advanced Courses', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 423,
    images: ['https://image.pollinations.ai/prompt/Snow%20activities%20and%20mountains%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Kashmir Honeymoon Package',
    description: 'Complete Kashmir Valley - Srinagar Dal Lake, Gulmarg meadow of flowers, Pahalgam valley of shepherds, Sonmarg meadow of gold. Romantic houseboat stay, gondola rides, apple orchards, snow-capped peaks.',
    destination: 'Kashmir Valley',
    state: 'Jammu & Kashmir',
    price: 24999,
    duration: { days: 6, nights: 5 },
    category: 'Honeymoon',
    hotel: { name: 'Luxury Houseboat + Hotels', rating: 5, type: 'Luxury' },
    transport: { type: 'Mixed', details: 'Private cab throughout' },
    highlights: ['Srinagar', 'Gulmarg', 'Pahalgam', 'Sonmarg', 'Houseboat', 'Gondola'],
    inclusions: ['Private Transportation', 'Luxury Stay', 'All Meals', 'Shikara Ride', 'Gondola', 'Sightseeing', 'Guide'],
    exclusions: ['Airfare', 'Personal Expenses', 'Insurance'],
    rating: 4.9,
    reviewCount: 689,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Romantic%20Kashmir%20scenery%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // PUNJAB, UTTAR PRADESH, MADHYA PRADESH
  {
    title: 'Amritsar Golden Temple Tour',
    description: 'Spiritual journey - Golden Temple Harmandir Sahib, Jallianwala Bagh martyrs memorial, Wagah Border flag ceremony patriotic. Langar community kitchen experience and vibrant Punjabi culture food.',
    destination: 'Amritsar',
    state: 'Punjab',
    price: 7999,
    duration: { days: 3, nights: 2 },
    category: 'Pilgrimage',
    hotel: { name: 'Ramada Amritsar', rating: 4, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + local transport' },
    highlights: ['Golden Temple', 'Wagah Border', 'Jallianwala Bagh', 'Langar', 'Partition Museum', 'Punjabi Food'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast & Dinner', 'Sightseeing', 'Wagah Border Seats', 'Guide'],
    exclusions: ['Train Fare', 'Lunch', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 923,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Golden%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Agra Taj Mahal Tour',
    description: 'Wonder of the World - Taj Mahal sunrise visit monument of love, Agra Fort UNESCO heritage, Fatehpur Sikri ghost city, Mehtab Bagh sunset view. Mughal architecture and marble inlay work.',
    destination: 'Agra',
    state: 'Uttar Pradesh',
    price: 6999,
    duration: { days: 2, nights: 1 },
    category: 'Cultural',
    hotel: { name: 'Hotel Taj Resorts', rating: 4, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + local cab' },
    highlights: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh', 'Marble Inlay', 'Local Crafts'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast', 'Sightseeing', 'Guide', 'Entry Tickets', 'Sunrise Visit'],
    exclusions: ['Train Fare', 'Lunch & Dinner', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 1234,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Taj%20Mahal%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Varanasi Spiritual Journey',
    description: 'Oldest living city - Ganga Aarti evening ceremony, boat ride at sunrise ghats, Kashi Vishwanath Temple golden temple, ghats walk spiritual. Sarnath where Buddha preached. Profound spiritual experience.',
    destination: 'Varanasi',
    state: 'Uttar Pradesh',
    price: 9999,
    duration: { days: 3, nights: 2 },
    category: 'Pilgrimage',
    hotel: { name: 'Radisson Varanasi', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Airport pickup + boat' },
    highlights: ['Ganga Aarti', 'Boat Ride', 'Kashi Temple', 'Sarnath', 'Ghats Walk', 'Evening Prayers'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Boat Ride', 'Temple Visit', 'Guide', 'Aarti Arrangements'],
    exclusions: ['Airfare', 'Donations', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 756,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Ganga%20ghats%20and%20temples%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Khajuraho Heritage Tour',
    description: 'UNESCO World Heritage temples with intricate erotic sculptures Chandela dynasty art. Medieval art and architecture masterpiece temples. Light & sound show evening. Panna National Park optional tiger reserve.',
    destination: 'Khajuraho',
    state: 'Madhya Pradesh',
    price: 11999,
    duration: { days: 3, nights: 2 },
    category: 'Cultural',
    hotel: { name: 'Radisson Khajuraho', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Flight + local cab' },
    highlights: ['Khajuraho Temples', 'Sculpture Art', 'Light & Sound', 'Panna National Park', 'Heritage Walk', 'Museum'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Light & Sound Show', 'Guide', 'Tickets'],
    exclusions: ['Airfare', 'Panna Safari', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 445,
    images: ['https://image.pollinations.ai/prompt/Khajuraho%20temples%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Bandhavgarh Wildlife Safari',
    description: 'Highest tiger density in India. Multiple jungle safari slots, wildlife photography opportunities, ancient Bandhavgarh Fort hilltop, jungle rides elephant and jeep. Best tiger sighting chances in India. Nature trails.',
    destination: 'Bandhavgarh',
    state: 'Madhya Pradesh',
    price: 19999,
    duration: { days: 4, nights: 3 },
    category: 'Wildlife',
    hotel: { name: 'Infinity Resorts', rating: 4, type: 'Premium' },
    transport: { type: 'Flight', details: 'Flight + jeep safari' },
    highlights: ['Tiger Safari', 'Wildlife Photography', 'Bandhavgarh Fort', 'Jungle Rides', 'Nature Trails', 'Bird Watching'],
    inclusions: ['Transportation', 'Resort Stay', 'All Meals', 'Multiple Safaris', 'Naturalist Guide', 'Permits'],
    exclusions: ['Airfare', 'Camera Fees', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 312,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Tigers%20and%20jungle%20safari%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // GUJARAT, WEST BENGAL, ODISHA
  {
    title: 'Statue of Unity Tour',
    description: 'World\'s tallest statue 182m - Sardar Vallabhbhai Patel monument tribute, Valley of Flowers botanical garden, laser light show, Narmada river view, Sardar Sarovar Dam engineering marvel. Museum and exhibition.',
    destination: 'Kevadia',
    state: 'Gujarat',
    price: 8499,
    duration: { days: 3, nights: 2 },
    category: 'Cultural',
    hotel: { name: 'Tent City Narmada', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Statue of Unity', 'Valley of Flowers', 'Laser Show', 'Sardar Sarovar Dam', 'Museum', 'River View'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Entry Tickets', 'Laser Show', 'Guide', 'Museum Visit'],
    exclusions: ['Personal Expenses', 'Photography Fees'],
    rating: 4.6,
    reviewCount: 634,
    images: ['https://image.pollinations.ai/prompt/Statue%20of%20Unity%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Rann of Kutch Festival Package',
    description: 'White desert festival November-February - Cultural performances folk dances, handicrafts villages traditional, camel safari desert, full moon nights magical. Unique desert experience. Kutch embroidery and crafts.',
    destination: 'Kutch',
    state: 'Gujarat',
    price: 13999,
    duration: { days: 4, nights: 3 },
    category: 'Cultural',
    hotel: { name: 'Rann Utsav Tent City', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Bhuj airport + cab' },
    highlights: ['White Rann', 'Rann Utsav', 'Cultural Shows', 'Handicraft Villages', 'Desert Safari', 'Full Moon Night'],
    inclusions: ['Transportation', 'Tent Stay', 'All Meals', 'Cultural Shows', 'Village Tours', 'Camel Ride', 'Guide'],
    exclusions: ['Airfare', 'Shopping', 'Personal Expenses'],
    rating: 4.9,
    reviewCount: 498,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/White%20desert%20and%20festival%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Darjeeling Tea Estate Tour',
    description: 'Queen of Himalayas - Toy train UNESCO heritage, Tiger Hill sunrise Kanchenjunga view, tea gardens visit and tasting, Happy Valley tea estate, Himalayan Zoo red panda. Buddhist monasteries peace pagoda.',
    destination: 'Darjeeling',
    state: 'West Bengal',
    price: 10999,
    duration: { days: 4, nights: 3 },
    category: 'Hill Station',
    hotel: { name: 'Windamere Hotel', rating: 4, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + toy train + cab' },
    highlights: ['Toy Train', 'Tiger Hill', 'Tea Gardens', 'Himalayan Zoo', 'Monasteries', 'Kanchenjunga View'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Toy Train', 'Sightseeing', 'Tea Estate Visit', 'Guide'],
    exclusions: ['Train to NJP', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 523,
    images: ['https://image.pollinations.ai/prompt/Tea%20gardens%20and%20mountains%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Sundarbans Wildlife Package',
    description: 'Largest mangrove forest UNESCO - Royal Bengal Tiger habitat, saltwater crocodiles, boat safaris creek exploration, bird watching paradise, village tour local life. Unique ecosystem. Delta beauty.',
    destination: 'Sundarbans',
    state: 'West Bengal',
    price: 14999,
    duration: { days: 3, nights: 2 },
    category: 'Wildlife',
    hotel: { name: 'Sundarban Tiger Camp', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'Bus + boat safari' },
    highlights: ['Tiger Spotting', 'Boat Safari', 'Mangroves', 'Bird Watching', 'Village Tour', 'Crocodile Viewing'],
    inclusions: ['Transportation', 'Resort Stay', 'All Meals', 'Boat Safaris', 'Naturalist Guide', 'Permits'],
    exclusions: ['Personal Expenses', 'Insurance'],
    rating: 4.6,
    reviewCount: 287,
    images: ['https://image.pollinations.ai/prompt/Mangrove%20forests%20and%20wildlife%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Puri Jagannath Tour',
    description: 'Sacred pilgrimage - Lord Jagannath Temple one of Char Dham, Puri Beach golden sands, Chilika Lake Asia\'s largest brackish water lagoon dolphins, Konark Sun Temple UNESCO chariot architecture. Spiritual coastal experience.',
    destination: 'Puri',
    state: 'Odisha',
    price: 8999,
    duration: { days: 3, nights: 2 },
    category: 'Pilgrimage',
    hotel: { name: 'Mayfair Beach Resort', rating: 4, type: 'Standard' },
    transport: { type: 'Train', details: 'Train + cab' },
    highlights: ['Jagannath Temple', 'Puri Beach', 'Chilika Lake', 'Konark Temple', 'Rath Yatra', 'Mahaprasad'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Temple Darshan', 'Boat Ride', 'Sightseeing', 'Guide'],
    exclusions: ['Train Fare', 'Donations', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 678,
    images: ['https://image.pollinations.ai/prompt/Jagannath%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Konark Heritage Package',
    description: 'Sun Temple UNESCO World Heritage - Architectural marvel Black Pagoda, chariot wheels sundial, Chandrabhaga Beach pristine, erotic sculptures ancient art. Kalinga architecture masterpiece. ASI museum artifacts.',
    destination: 'Konark',
    state: 'Odisha',
    price: 7999,
    duration: { days: 2, nights: 1 },
    category: 'Cultural',
    hotel: { name: 'Lotus Eco Resort', rating: 3, type: 'Standard' },
    transport: { type: 'Bus', details: 'AC bus + local transport' },
    highlights: ['Sun Temple', 'Chariot Wheels', 'Chandrabhaga Beach', 'ASI Museum', 'Sculptures', 'Dance Festival'],
    inclusions: ['Transportation', 'Hotel', 'Breakfast & Dinner', 'Temple Visit', 'Guide', 'Entry Tickets'],
    exclusions: ['Lunch', 'Personal Expenses'],
    rating: 4.6,
    reviewCount: 445,
    images: ['https://image.pollinations.ai/prompt/Konark%20Sun%20Temple%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },

  // SIKKIM, ASSAM, MEGHALAYA, LADAKH
  {
    title: 'Gangtok Himalayan Tour',
    description: 'Himalayan gem - Tsomgo Lake glacial sacred, Nathula Pass Indo-China border 14000ft, Rumtek Monastery Tibetan Buddhism, MG Marg pedestrian street. Cable car ropeway, clean scenic mountain town Buddhist culture.',
    destination: 'Gangtok',
    state: 'Sikkim',
    price: 13999,
    duration: { days: 5, nights: 4 },
    category: 'Hill Station',
    hotel: { name: 'The Elgin Nor-Khill', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Bagdogra airport + cab' },
    highlights: ['Tsomgo Lake', 'Nathula Pass', 'Rumtek Monastery', 'MG Marg', 'Cable Car', 'Banjhakri Falls'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Permits', 'Sightseeing', 'Guide', 'Entry Tickets'],
    exclusions: ['Airfare', 'Personal Expenses'],
    rating: 4.8,
    reviewCount: 567,
    featured: true,
    images: ['/assets/manali_hero_banner_1780120753614.png']
  },
  {
    title: 'North Sikkim Adventure',
    description: 'High altitude adventure - Lachung flower village, Lachen remote valley, Yumthang Valley valley of flowers rhododendrons, Zero Point snow desert, Gurudongmar Lake sacred 17000ft. Snow-covered peaks pristine landscapes.',
    destination: 'North Sikkim',
    state: 'Sikkim',
    price: 18999,
    duration: { days: 6, nights: 5 },
    category: 'Adventure',
    hotel: { name: 'Mountain Lodges', rating: 3, type: 'Standard' },
    transport: { type: 'Mixed', details: 'SUV throughout' },
    highlights: ['Yumthang Valley', 'Gurudongmar Lake', 'Zero Point', 'Lachung', 'Lachen', 'Hot Springs'],
    inclusions: ['SUV Transportation', 'Hotel Stay', 'All Meals', 'Permits', 'Oxygen Support', 'Local Guide'],
    exclusions: ['Airfare to Bagdogra', 'Personal Expenses', 'Medical Kit'],
    rating: 4.7,
    reviewCount: 312,
    images: ['https://image.pollinations.ai/prompt/Snow%20mountains%20and%20valleys%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Kaziranga Wildlife Safari',
    description: 'One-horned Rhino sanctuary UNESCO - Elephant safari early morning, jeep safari multiple zones, tea garden visits Assam tea, bird watching paradise 500+ species. UNESCO World Heritage highest rhino density globally.',
    destination: 'Kaziranga',
    state: 'Assam',
    price: 16999,
    duration: { days: 4, nights: 3 },
    category: 'Wildlife',
    hotel: { name: 'Infinity Resorts', rating: 4, type: 'Premium' },
    transport: { type: 'Flight', details: 'Jorhat airport + cab' },
    highlights: ['Rhino Safari', 'Elephant Ride', 'Jeep Safari', 'Tea Gardens', 'Bird Watching', 'River Cruise'],
    inclusions: ['Transportation', 'Resort Stay', 'All Meals', 'Multiple Safaris', 'Naturalist Guide', 'Permits'],
    exclusions: ['Airfare', 'Camera Fees', 'Personal Expenses'],
    rating: 4.9,
    reviewCount: 423,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/One-horned%20rhinoceros%20safari%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Shillong & Cherrapunji Tour',
    description: 'Scotland of East - Living root bridges natural wonder, Cherrapunji wettest place on earth, Mawlynnong cleanest village Asia, Umiam Lake scenic, waterfalls Nohkalikai Seven Sisters. Unique natural wonders caves limestone.',
    destination: 'Shillong',
    state: 'Meghalaya',
    price: 12999,
    duration: { days: 5, nights: 4 },
    category: 'Hill Station',
    hotel: { name: 'Polo Towers', rating: 4, type: 'Standard' },
    transport: { type: 'Flight', details: 'Guwahati airport + cab' },
    highlights: ['Living Root Bridge', 'Cherrapunji', 'Mawlynnong', 'Umiam Lake', 'Waterfalls', 'Caves'],
    inclusions: ['Transportation', 'Hotel', 'All Meals', 'Sightseeing', 'Trekking Guide', 'Entry Tickets'],
    exclusions: ['Airfare', 'Personal Expenses'],
    rating: 4.7,
    reviewCount: 398,
    images: ['https://image.pollinations.ai/prompt/Meghalaya%20waterfalls%20and%20valleys%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Leh Ladakh Bike Expedition',
    description: 'Ultimate biking adventure - Khardung La world\'s highest motorable road 18380ft, Pangong Lake 3-Idiots fame blue waters, Nubra Valley sand dunes camels, Magnetic Hill gravity hill. Challenging terrain experienced riders mountain passes.',
    destination: 'Leh Ladakh',
    state: 'Ladakh',
    price: 34999,
    duration: { days: 10, nights: 9 },
    category: 'Adventure',
    hotel: { name: 'Guesthouses & Camps', rating: 2, type: 'Budget' },
    transport: { type: 'Self-Drive', details: 'Bike rental + fuel' },
    highlights: ['Khardung La Pass', 'Pangong Lake', 'Nubra Valley', 'Magnetic Hill', 'Bike Expedition', 'High Passes'],
    inclusions: ['Bike Rental', 'Accommodation', 'Breakfast & Dinner', 'Permits', 'Support Vehicle', 'Mechanic'],
    exclusions: ['Bike Fuel', 'Lunch', 'Personal Expenses', 'Insurance', 'Medical Kit'],
    rating: 4.9,
    reviewCount: 734,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Bikes%20on%20Ladakh%20roads%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Pangong Lake Adventure',
    description: 'High altitude lake 14270ft - Crystal blue waters color changing, camping under stars lakeside, monasteries ancient Buddhist, Leh market shopping Tibetan, Shanti Stupa peace pagoda. Bollywood 3 Idiots famous location.',
    destination: 'Pangong Lake',
    state: 'Ladakh',
    price: 19999,
    duration: { days: 6, nights: 5 },
    category: 'Adventure',
    hotel: { name: 'Hotel + Camps', rating: 3, type: 'Standard' },
    transport: { type: 'Mixed', details: 'SUV + camping' },
    highlights: ['Pangong Lake', 'Leh Palace', 'Shanti Stupa', 'Nubra Valley', 'Monasteries', 'Camping'],
    inclusions: ['SUV Transportation', 'Hotel + Camp', 'All Meals', 'Permits', 'Camping Equipment', 'Guide'],
    exclusions: ['Airfare', 'Personal Expenses', 'Insurance'],
    rating: 4.8,
    reviewCount: 612,
    featured: true,
    images: ['https://image.pollinations.ai/prompt/Pangong%20Lake%2C%20Ladakh%2C%20ultra-realistic%20travel%20photography%2C%204K%2C%20vibrant%20colors%2C%20cinematic%20composition?width=800&height=600&nologo=true']
  },
  {
    title: 'Andaman Island Paradise Package',
    description: 'Tropical paradise - Radhanagar Beach Asia\'s best beach white sands, Cellular Jail freedom struggle history, Havelock Island scuba diving snorkeling, Neil Island coral reefs. Pristine islands turquoise waters water sports.',
    destination: 'Port Blair',
    state: 'Andaman & Nicobar',
    price: 24999,
    duration: { days: 6, nights: 5 },
    category: 'Beach',
    hotel: { name: 'Sea Shell Resort', rating: 4, type: 'Premium' },
    transport: { type: 'Flight', details: 'Flight + ferry + cab' },
    highlights: ['Radhanagar Beach', 'Cellular Jail', 'Havelock Island', 'Scuba Diving', 'Neil Island', 'Water Sports'],
    inclusions: ['Transportation', 'Hotel Stay', 'All Meals', 'Ferry Tickets', 'Scuba Diving', 'Sightseeing', 'Guide'],
    exclusions: ['Airfare', 'Personal Expenses', 'Additional Water Sports'],
    rating: 4.9,
    reviewCount: 789,
    featured: true,
    images: ['/assets/goa_hero_banner_1780120545332.png']
  }
];

// MongoDB connection and seeding function
mongoose.connect(MONGODB_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('✅ Connected to MongoDB');
    
    // Insert packages
    try {
      const inserted = await Package.insertMany(packagesData);
      console.log(`🎉 Successfully seeded ${inserted.length} India tour packages`);
      console.log('📦 Package categories:', [...new Set(packagesData.map(p => p.category))]);
      console.log('🗺️  States covered:', [...new Set(packagesData.map(p => p.state))].length);
    } catch (err) {
      console.error('❌ Error inserting packages:', err);
    }

    mongoose.disconnect();
  })
  .catch(err => {
    console.error('❌ Connection error:', err);
  });
